### ISSUE TITLE
Questions about reproducing scores

### ISSUE THREAD

**Issue by danieldeutsch** [PierreColombo/nlg_eval_via_simi_measures#2]
Hello,

I am having trouble reproducing the scores from the toy example Jupyter Notebook. I want to make sure I have faithfully reproduced the results from the metrics when I incorporate them into Repro.

Here are some issues I'm running into:
- Could you provide a requirements.txt with the package versions you are using (e.g., what transformers/pytorch versions)?
- The Jupyter Notebook passes in the references first (`metric_call.evaluate_batch(refs, hypothesis)`) but the `evaluate_batch` methods seem to expect the arguments in the opposite order
- When I run InfoLM on the GPU, there is a tensor which is still on the CPU. It occurs here:
```
File "/app/nlg_eval_via_simi_measures/infolm.py", line 280, in evaluate_batch
    dict_final_distribution_batch_refs, idfs_ref = self.get_distribution(batch_refs, idf_ref)
File "/app/nlg_eval_via_simi_measures/infolm.py", line 245, in get_distribution
    outputs = self.model(**unmasked_data, labels=labels)
...
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```
- It would also be very helpful to have the expected output for the data in the "samples" directory

Thanks!

**Comment by danieldeutsch** [comment]
It would also be very helpful for the CLI to have an option to write the per-input scores to a json file

**Comment by PierreColombo** [comment]
Can you give me your pytorch + transformers version ?

**Comment by PierreColombo** [comment]
Hi Daniel,
Thanks for opening the issue and for the comments.

I did the experiment on a supercompute i no longer have access to. So for the version feel free to choose the one you want. 

I corrected a typo in the Wasserstein and it should be working on GPU now. Thanks for pointing it out. 

I'll modify the CLI a bite later thanks for the suggestion.

If you find other bugs or fail to reproduce results feel free to tell me !

Cheers,

**Comment by PierreColombo** [comment]
You can check with the raw score folder if you face issues.

**Comment by danieldeutsch** [comment]
Thanks @PierreColombo.

[Here](https://github.com/danieldeutsch/repro/blob/colombo2021/models/colombo2021/Dockerfile) is the Dockerfile where I packaged up this repository. I couldn't find the expected output for the examples you provided (under the "samples" directory), but [this file](https://github.com/danieldeutsch/repro/blob/colombo2021/models/colombo2021/tests/fixtures/expected.json) shows the outputs from my wrappers.

If this looks ok to you, I will go and and merge the wrappers around your metric into my library.

Thanks!

**Comment by PierreColombo** [comment]
I think this look good ! If you pulled the very last version for baryscore then that is perfect ! Thanks a lot !

**Comment by danieldeutsch** [comment]
Great, I have merged the implementation into Repro. Thanks!

**Comment by PierreColombo** [comment]
Thanks for your great work :)
