### ISSUE TITLE
Reproduce MSCOCO and WebNLG

### ISSUE THREAD

**Issue by long21wt** [PierreColombo/nlg_eval_via_simi_measures#4]
Hi,

Could you provide scripts to compute the correlation score for MSCOCO and WebNLG ? I couldn't find any instruction for these 2 datasets.

Thanks

**Comment by PierreColombo** [comment]
For webnlg you need to parse the github for https://webnlg-challenge.loria.fr/workshop_2020/. For MSCOCO it is also available online. :)

**Comment by PierreColombo** [comment]
I plan to make a release of WebNLG asap.

**Comment by long21wt** [comment]
Close, as the author's script is not published
