### ISSUE TITLE
Make a package release

### ISSUE THREAD

**Issue by stancld** [PierreColombo/nlg_eval_via_simi_measures#6]
Hi @PierreColombo,

First of all, I'd like to thank you for the great work of you and your team in developing NLG metrics. I'm just curious if you'd be interested in my contribution to creating `setup.py` file and preparing other related stuff so that the repo can be installed from the source with `pip` and also make it potentially published via `pypi`. I believe this could help further adopt your evaluation metrics and make them easier to use for various use cases. Also, we would like to implement these metrics within [`torchmetrics`](https://github.com/PyTorchLightning/metrics) package (see [InfoLM](https://github.com/PyTorchLightning/metrics/issues/849), [BaryScore](https://github.com/PyTorchLightning/metrics/issues/852) and [DepthScore](https://github.com/PyTorchLightning/metrics/issues/854) issues), therefore, the possibility of installing the package from `pypi` would facilitate us to test our implementation against yours so that we can be sure our implementation is correct.

Thanks once again and please let me know what you do think about my proposal :]

cc: @Borda

**Comment by PierreColombo** [comment]
Hi !
Thanks a lot for your message and apologies for the late response. I had familly emergencies.

Your proposal looks great :) . We have some new metrics that we join the party as well !
