### ISSUE TITLE
Question about the robustness of the metric, seems easy to be affected by the candidate sentences

### ISSUE THREAD

**Issue by guihuzhang** [PierreColombo/nlg_eval_via_simi_measures#8]
We found the word frequency of candidate sentences might affect the score. We used the following codes to test the performance of InfoLM, but got different results for the same pair of candidate and reference sentences in different subsets. 

Firstly, we made the candidate and reference sentences exactly the same; as expected, the distances between sentences are 0. 

```
metric = InfoLM(measure_to_use='fisher_rao', alpha=0.5, beta=2, temperature=1.5, )
ref = [
       "germany produces what kind of beer?", ]
hypothesis = [
              "germany produces what kind of beer?", ]
metric.prepare_idfs(ref, hypothesis)
final_preds = metric.evaluate_batch(hypothesis, ref)
print(final_preds)
```
result: {'fisher_rao': [0.0], 'r_fisher_rao': [0.0], 'sim_fisher_rao': [0.0]}

However, when we make the set of candidate and reference sentences different, but including one exactly the same sentence inside each, the distance between these two sentences is not 0, 

```
metric = InfoLM(measure_to_use='fisher_rao', alpha=0.5, beta=2, temperature=1.5, )
ref = [
       "name all of the rivers located in china.",
       "germany produces what kind of beer?",
       "lisp was designed by who?",
       "which of the bassists has a height of at least 1.94?",
       "name the aircraft that has the least amount of cargo space.",
       "what building has the earliest construction starting date?",
       "what lighthouses were constructed with sandstones?",
       "germany produces what kind of beer?",
       "belgium produces what kind of beer?",
       "belgium produces what kind of wine?",
       "belgium produces what type of wine?",
       "belgium produces which type of wine?",
       "belgium has which type of wine?",
       ]
hypothesis = [
              "name all of the rivers located in korea.",
              "france produces what kind of beer?",
              "ocaml was designed by who?",
              "which of the bassists has a height of at most 1.94?",
              "name the aircraft that has the most amount of cargo space.",
              "what building has the oldest construction starting date?",
              "what lighthouses were constructed with cements?",
              "germany produces what kind of beer?",
              "germany produces what kind of beer?",
              "germany produces what kind of beer?",
              "germany produces what kind of beer?",
              "germany produces what kind of beer?",
              "germany produces what kind of beer?"
]
metric.prepare_idfs(ref, hypothesis)
final_preds = metric.evaluate_batch(hypothesis, ref)
print(final_preds)
```
result: {'fisher_rao': [0.13154096901416779, 0.3968910872936249, 0.8951906561851501, 0.17877444624900818, 0.3418828845024109, 0.28145506978034973, 0.42686304450035095, **0.23330892622470856**, 0.4328637421131134, 0.5381670594215393, 0.6704646348953247, 0.8761745095252991, 0.7861247658729553], 
'r_fisher_rao': [0.13154096901416779, 0.3968910872936249, 0.8951906561851501, 0.17877444624900818, 0.3418828845024109, 0.28145506978034973, 0.42686304450035095, **0.23330892622470856**, 0.4328637421131134, 0.5381670594215393, 0.6704646348953247, 0.8761745095252991, 0.7861247658729553], '
sim_fisher_rao': [0.13154096901416779, 0.3968910872936249, 0.8951906561851501, 0.17877444624900818, 0.3418828845024109, 0.28145506978034973, 0.42686304450035095, **0.23330892622470856**, 0.4328637421131134, 0.5381670594215393, 0.6704646348953247, 0.8761745095252991, 0.7861247658729553]}

Here we found that exactly the same sentence, "germany produces what kind of beer?" in reference and candidate sets don’t lead to a 0 distance, but their distance is 0.23330892622470856 according to the code you provided. 

After reading the paper carefully, we found that the word frequency in candidate sentences might affect the InfoLM score. On page 3 of your paper, you wrote “where $\widetilde{γ_k}$ and $γ_k$ are measures of the importance of the k-th token in the candidate and reference text, respectively”. From our understanding, since the set of candidate sentences each time might be different, then if each time you compute the IDF of words according to the candidate sentences, the distance obtained for a given (fixed)  pair of (candidate sentence, reference sentence) could be different at each time of testing. Would you confirm our understanding here - is this a feature from the design your metric? 

Thank you for spending some time reading our mail. I’d appreciate it if you could help me with my questions.

**Comment by PierreColombo** [comment]
I we solve the problem via mail. It was a missunderstanding when reading the paper.
